# Generated by Django 5.0.3 on 2025-07-29 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hw1', '0003_vcfdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VcfData',
        ),
    ]
