# Generated by Django 5.0.3 on 2025-07-29 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw1', '0004_delete_vcfdata'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='existjobs',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='existjobs',
            name='user_id',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
