# Generated by Django 5.0.3 on 2025-08-18 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw1', '0005_alter_existjobs_managers_existjobs_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='existjobs',
            name='diagnosis',
            field=models.TextField(default='N/A'),
        ),
    ]
