# Generated by Django 5.0.3 on 2026-01-21 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw1', '0006_existjobs_diagnosis'),
    ]

    operations = [
        migrations.AddField(
            model_name='existjobs',
            name='genome_build',
            field=models.CharField(default='hg19', max_length=10),
        ),
    ]
