import React,{useRef,useState} from 'react';
import {Alert,Box,Button,LinearProgress,Paper,Stack,TextField,Typography} from '@mui/material';
import axios from 'axios'; import {useNavigate} from 'react-router-dom'; import {config} from '../../../constant';
import {cardSx,contentSx,pageSx,primaryButtonSx,secondaryButtonSx} from '../WGS_Germline/wgsUi';
const specs=[['snv','SNV/Indel VCF',true,/\.vcf\.(gz|bgz)$/i,'.vcf.gz,.vcf.bgz','Single-sample GRCh38 compressed VCF produced by the caller.'],['sv','Structural Variant VCF',false,/\.vcf\.(gz|bgz)$/i,'.vcf.gz,.vcf.bgz','Optional structural-variant callset.'],['cnv','Copy Number VCF',false,/\.vcf\.(gz|bgz)$/i,'.vcf.gz,.vcf.bgz','Optional copy-number callset.'],['callable','Callable regions',false,/\.(bed|bed\.gz|zip)$/i,'.bed,.bed.gz,.zip','Optional callable BED used only for an exploratory coding TMB estimate.']];
function Input({label,required,file,setFile,accept,description}){const ref=useRef();return <Paper sx={{...cardSx,border:required?'1px solid #93bddd':'1px dashed #b8c7d3'}}><Stack direction="row" spacing={1} alignItems="center"><Typography variant="h6" fontWeight={750}>{label}</Typography><Typography variant="caption" sx={{px:1,py:.3,borderRadius:4,bgcolor:required?'primary.main':'grey.200',color:required?'white':'text.secondary',fontWeight:800}}>{required?'REQUIRED':'OPTIONAL'}</Typography></Stack><Typography color="text.secondary" variant="body2" sx={{mt:.5}}>{description}</Typography><Stack direction="row" spacing={2} sx={{mt:2}}><input hidden ref={ref} type="file" accept={accept} onChange={e=>setFile(e.target.files?.[0]||null)}/><TextField fullWidth disabled value={file?.name||''} placeholder={required?'Select a compressed VCF':'Skip when unavailable'}/><Button variant={required?'contained':'outlined'} onClick={()=>ref.current.click()}>Browse</Button>{file&&<Button color="inherit" onClick={()=>setFile(null)}>Clear</Button>}</Stack></Paper>}
export default function WgsSomaticSample(){const nav=useNavigate();const [files,setFiles]=useState({});const [error,setError]=useState('');const [progress,setProgress]=useState(0);const valid=files.snv&&specs.every(([k,,required,pattern])=>!files[k]?!required:pattern.test(files[k].name));
const upload=async()=>{if(!valid)return setError('A compressed SNV/Indel VCF is required.');const draft=JSON.parse(sessionStorage.getItem('wgsSomaticDraft')||'{}');const body=new FormData();body.append('draft_id',draft.draft_id);specs.forEach(([k])=>{if(files[k])body.append(k,files[k])});try{const {data}=await axios.post(`${config.rootApiIP}/wgs-somatic/uploads`,body,{onUploadProgress:e=>setProgress(e.total?Math.round(e.loaded*100/e.total):0)});sessionStorage.setItem('wgsSomaticDraft',JSON.stringify({...draft,upload_id:data.upload_id}));nav(`${config.rootPathPrefix}/Analysis/WGS_Somatic/Settings`);}catch(e){setError(e.response?.data?.detail||'Upload failed.');}};
return <Box sx={pageSx}><Box sx={contentSx}>
  <Typography variant="h3" fontWeight={800}>Tumor callsets</Typography>
  <Typography color="text.secondary" sx={{mb:2}}>SNV/Indel is required. Other inputs are optional and omitted inputs do not block the job.</Typography>
  <Alert severity="info" sx={{mb:2}}>VCFs are validated as single-sample GRCh38 callsets. Callable regions enable an estimated—not clinical—TMB result.</Alert>
  {error&&<Alert severity="error">{error}</Alert>}
  <Stack spacing={2} sx={{mt:2}}>{specs.map(([k,l,r,pattern,accept,description])=><Input key={k} label={l} required={r} file={files[k]} accept={accept} description={description} setFile={f=>setFiles({...files,[k]:f})}/>)}</Stack>
  {progress>0&&<LinearProgress variant="determinate" value={progress} sx={{mt:2}}/>}
  <Stack direction="row" spacing={2} justifyContent="center" sx={{mt:4}}><Button sx={secondaryButtonSx} onClick={()=>nav(`${config.rootPathPrefix}/Analysis/WGS_Somatic/Subject`)}>Previous</Button><Button variant="contained" sx={primaryButtonSx} disabled={!valid} onClick={upload}>Continue</Button></Stack>
</Box></Box>}
