import React,{useRef,useState} from 'react';
import {Alert,Box,Button,LinearProgress,Paper,Stack,TextField,Typography} from '@mui/material';
import axios from 'axios'; import {useNavigate} from 'react-router-dom'; import {config} from '../../../constant';
import {cardSx,contentSx,pageSx,primaryButtonSx,secondaryButtonSx} from '../WGS_Germline/wgsUi';
const specs=[['snv','SNV/Indel VCF'],['sv','Structural Variant VCF'],['cnv','Copy Number VCF']];
function Input({kind,label,file,setFile}){const ref=useRef();return <Paper sx={cardSx}><Typography variant="h6" fontWeight={750}>{label}</Typography><Typography color="text.secondary" variant="body2">Single-sample GRCh38 .vcf.gz produced by the caller</Typography><Stack direction="row" spacing={2} sx={{mt:2}}><input hidden ref={ref} type="file" accept=".vcf.gz,.vcf.bgz,.gz" onChange={e=>setFile(e.target.files?.[0]||null)}/><TextField fullWidth disabled value={file?.name||''}/><Button variant="contained" onClick={()=>ref.current.click()}>Browse</Button></Stack></Paper>}
export default function WgsSomaticSample(){const nav=useNavigate();const [files,setFiles]=useState({});const [error,setError]=useState('');const [progress,setProgress]=useState(0);const valid=specs.every(([k])=>files[k]&&/\.vcf\.(gz|bgz)$/i.test(files[k].name));
const upload=async()=>{if(!valid)return setError('All three compressed VCF files are required.');const draft=JSON.parse(sessionStorage.getItem('wgsSomaticDraft')||'{}');const body=new FormData();body.append('draft_id',draft.draft_id);specs.forEach(([k])=>body.append(k,files[k]));try{const {data}=await axios.post(`${config.rootApiIP}/wgs-somatic/uploads`,body,{onUploadProgress:e=>setProgress(e.total?Math.round(e.loaded*100/e.total):0)});sessionStorage.setItem('wgsSomaticDraft',JSON.stringify({...draft,upload_id:data.upload_id}));nav(`${config.rootPathPrefix}/Analysis/WGS_Somatic/Settings`);}catch(e){setError(e.response?.data?.detail||'Upload failed.');}};
return <Box sx={pageSx}><Box sx={contentSx}><Typography variant="h3" fontWeight={800}>Tumor callsets</Typography><Typography color="text.secondary" sx={{mb:3}}>Files are reheadered to the platform sample ID and validated as GRCh38.</Typography>{error&&<Alert severity="error">{error}</Alert>}<Stack spacing={2} sx={{mt:2}}>{specs.map(([k,l])=><Input key={k} kind={k} label={l} file={files[k]} setFile={f=>setFiles({...files,[k]:f})}/>)}</Stack>{progress>0&&<LinearProgress variant="determinate" value={progress} sx={{mt:2}}/>}<Stack direction="row" spacing={2} justifyContent="center" sx={{mt:4}}><Button sx={secondaryButtonSx} onClick={()=>nav(`${config.rootPathPrefix}/Analysis/WGS_Somatic/Subject`)}>Previous</Button><Button variant="contained" sx={primaryButtonSx} disabled={!valid} onClick={upload}>Continue</Button></Stack></Box></Box>}
