# Generated by Django 5.0.3 on 2024-05-08 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='existJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobID', models.CharField(max_length=20)),
                ('subject_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('dob', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=10)),
                ('history', models.TextField(blank=True)),
            ],
        ),
    ]
