# Generated by Django 5.0.3 on 2024-05-13 10:15

import django.db.models.manager
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='existjobs',
            managers=[
                ('jobs', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='existjobs',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='existjobs',
            name='processID',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='existjobs',
            name='resultFile_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='existjobs',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='existjobs',
            name='uploadFile_url',
            field=models.URLField(blank=True),
        ),
    ]
