# Generated by Django 5.0.3 on 2024-12-03 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw1', '0002_alter_existjobs_managers_existjobs_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VcfData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chr', models.CharField(blank=True, max_length=10, null=True)),
                ('start', models.IntegerField(blank=True, null=True)),
                ('end', models.IntegerField(blank=True, db_column='End', null=True)),
                ('ref', models.CharField(blank=True, max_length=255, null=True)),
                ('alt', models.CharField(blank=True, max_length=255, null=True)),
                ('func_refgene', models.CharField(blank=True, max_length=255, null=True)),
                ('gene_refgene', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'vcf_data',
                'managed': False,
            },
        ),
    ]
