server {
  listen 80;
  server_name 140.116.66.190;
  return 301 https://$host$request_uri;
}

server {
  listen 443 ssl;
  server_name 140.116.66.190;
  client_max_body_size 0;

  ssl_certificate /etc/nginx/tls/platform.crt;
  ssl_certificate_key /etc/nginx/tls/platform.key;
  ssl_protocols TLSv1.2 TLSv1.3;

  location = / {
    return 302 /variant/login;
  }

  location / {
    proxy_pass http://frontend:80;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto https;
    proxy_connect_timeout 30s;
    proxy_send_timeout 360s;
    proxy_read_timeout 360s;
  }
}
